### ISSUE TITLE
Request appends `null` to path in Node v10

### ISSUE THREAD

**Issue by matthew-dean** [ZaralDev/node-request#2]
In this section:
```js
 	const options = {
 		hostname: parsedUrl.hostname,
 		port: parsedUrl.port,
 		path: parsedUrl.pathname + parsedUrl.search,
 		method: method,
 		headers: headers
	 };
```
...the value of `parsedUrl.search` can be null, meaning that the path ends up like `http://example.com/file.jsnull`

**Comment by ZaralDev** [comment]
Hey ! Thank you for the issue. Gonna fix it in the week ;)

**Comment by ZaralDev** [comment]
Fixed in https://github.com/ZaralDev/node-request/commit/30954efb81b8dd1ea1dcf822b97fab339d3af8b2
